name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Build stage
      - name: Build stage
        run: echo "Building application..."

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages     # branch to push to
          publish_dir: ./              # folder containing index.html
          force_orphan: true           # << important for fresh repo
          force: true 
          user_name: "github-actions"
          user_email: "github-actions@github.com"
